### ISSUE TITLE
Illumina data

### ISSUE THREAD

**Issue by DuttaAnik** [LiaOb21/colora#2]
Hi,
Thanks for developing the pipeline. I was wondering if it will support Illumina sequence data along with Pacbio/ONT.

Please let me know.

**Comment by LiaOb21** [comment]
Hi Anik,

At the moment Colora doesn't support Illumina data. The contigs are assembled with Hifiasm from PacBio HiFi, which are mandatory input, and optionally ONT (if you have them available). Then Hi-C reads are used for the assembly scaffolding with YaHS. 

We don't currently have a plan to include Illumina in the process.
Thank you for your question. :blush: 
Cheers,

Lia

**Comment by DuttaAnik** [comment]
Hi Lia,
Thank you very much for the prompt reply.
